app.name=QuadroFleet
server.port=8090
map.url=http://localhost:8090

telemetry.stream.receiver.port=2223
telemetry.stream.receiver.interval=1

controller.stream.target.ip=10.253.0.2
controller.stream.target.port=2223
controller.stream.target.interval=20

oipc.stream.receiver.port=2224
oipc.stream.receiver.interval=1

gstreamer.pipeline=udpsrc port=10900 ! application/x-rtp, encoding-name=H265, payload=96 ! rtph265depay ! h265parse ! avdec_h265 ! videoscale ! videoconvert
gstreamer.width=1280
gstreamer.height=720