server.port=8090
map.url=http://localhost:8090
video.stream.receiver.port=10900
telemetry.stream.receiver.port=2223
telemetry.stream.receiver.interval=1
controller.stream.target.ip=10.253.0.2
controller.stream.target.port=2223
controller.stream.target.interval=20